# Generated by Django 3.0.8 on 2020-07-24 18:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('inbound', models.CharField(max_length=100)),
                ('outbound', models.URLField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_browser_data', models.BooleanField(default=False)),
                ('correlation_id', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app.Link')),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['-created_on'],
            },
        ),
    ]
