# Generated by Django 3.0.8 on 2020-07-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='inbound',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
