# Generated by Django 3.2.16 on 2023-01-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200725_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='description',
        ),
        migrations.AlterField(
            model_name='entry',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='link',
            name='inbound',
            field=models.CharField(help_text='Path on the host without the initial and final slashes (e.g. some/path)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='outbound',
            field=models.URLField(help_text='Full URL to redirect to (e.g. https://google.com)'),
        ),
    ]
